version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Cefet123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver